baseurl = "https://kevcaz.github.io/"
relativeurls = true
languageCode = "en-us"
title = "KevCaz Home Page"
copyright = "&copy; 2019 Kevin Cazelles. "
theme = "hugo-KevCaz"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Kevin Cazelles"
  role = "Post-doctoral fellow in theoretical and computational ecology [@McCann Lab](https://mccannlab.ca/)"
  organization = "Department of Integrated Biology, University of Guelph"
  organization_url = "https://www.uoguelph.ca/ib/"
  # avatar = "kevcazava.jpg"
  twitter = "KCazelles"
  github = "KevCaz"
  address = "Department of Integrative Biology, Summerlee Science Complex, University of Guelph, Guelph, ON N1G 2W1"
  office_hours = "Send me an email for setting an appointment."
  email = "kcazelle@uoguelph.ca"
  phone = "+1 519 824 4120 (ext. 53700)"
  skype = "diazthc"
  skype_name = "Kevin Cazelles"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  #  For more info on the highlighting options, see:   # https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["bash", "julia", "python", "r", "rust", "xml", "yaml", "tex", "shell", "matlab"]
  highlight_style = "tomorrow-night-eighties"
  highlight_version = "9.15.8"

  # I follow the example given with highlightjs in academic theme to add mathjax and lealfet
  mathjax = true
  leaflet = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = [
    "/css/perso.css",
    "/css/family.css",
    "/css/creativecommons.css",
  ]
  custom_js  = [
    # "/js/mapoffice.js",
  ]


# Navigation Links

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Research"
    weight = 1

[[menu.main]]
    parent = "Research"
    name = "Projects"
    url = "/projects/"
    weight = 1
[[menu.main]]
    parent = "Research"
    name = "Publications"
    url = "/publications/"
    weight = 2
[[menu.main]]
    parent = "Research"
    name = "Software"
    url = "/software/"
    weight = 3
[[menu.main]]
    parent = "Research"
    name = "Software"
    url = "/software/"
    weight = 4
[[menu.main]]
    parent = "Research"
    name = "Talks&Posters"
    url = "/talks/"
    weight = 5
[[menu.main]]
    parent = "Research"
    name = "Teaching"
    url = "/teaching/"
    weight = 6
[[menu.main]]
    parent = "Research"
    name = "CV"
    url = "/cv/"
    weight = 7


[[menu.main]]
    name = "BlogPro"
    url = "/econotes/"
    weight = 6
[[menu.main]]
    parent = "BlogPro"
    name = "EcoNotes"
    url = "/econotes/"
    weight = 1
[[menu.main]]
    parent = "BlogPro"
    name = "SilicoNotes"
    url = "/notes/"
    weight = 2
[[menu.main]]
    parent = "BlogPro"
    name = "inSileco"
    url = "https://insileco.github.io/"
    weight = 3

[[menu.main]]
    name = "Perso"
    url = "/perso/"
    weight = 7
[[menu.main]]
    parent = "Perso"
    name = "Books I read and liked"
    url = "/perso/books"
    weight = 1
[[menu.main]]
    parent = "Perso"
    name = "Movies I watched and liked"
    url = "/perso/movies"
    weight = 2
[[menu.main]]
    parent = "Perso"
    name = "Opinions I dare to share"
    url = "/perso/opinions"
    weight = 3
[[menu.main]]
    parent = "Perso"
    name = "Even more personnal"
    url = "/perso/famille"
    weight = 4

# icon (font-awesome)
[[menu.icon]]
    name = "github"
    url = "https://github.com/KevCaz/KevCaz.github.io"


# Taxonomies.
[taxonomies]
  tag = "tags"
  topic = "topics"
  # category = "categories"

# Languages
# Create a [languages.X] block for each language you want, where X is the language ID.
# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
